# Generated by Django 2.0.6 on 2018-07-05 05:28

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_field_fix_and_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('organizations.organization',),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
            ],
            options={
                'indexes': [],
                'proxy': True,
            },
            bases=('organizations.organizationuser',),
        ),
    ]
